name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3 valgrind

    - name: build
      run: 
        make -B fast

    - name: run test suite
      run: 
        make test_suite

    - name: Publish executable
      uses: actions/upload-artifact@v4
      with:
        name: interpreter
        path: ./build/interpreter



    - name: clean  
      run: make clean
